= Ammar Ahmad Awan
:showtitle!:
:address: 2015 Neil Ave. • Columbus • OH 43210 • USA
:contact: +1 614 360 8349 • ammar.ahmad.awan@gmail.com
:website: http://cse.osu.edu/~awan.10

_{address}_ +
_{contact}_ +
_{website}_ 
 
== Publications

=== Select

. *A. A. Awan*, K. V. Manian, C-H Chu, H. Subramoni, and DK
Panda, _Optimized Large-Message Broadcast for Deep Learning
Workloads: MPI, MPI+NCCL, or NCCL2?_, Parallel Computing 
(*PARCO '19*), Vol. 85, Pages 141-152, Jul 2019.

. *A. A. Awan*, C-H Chu, X. Lu, H. Subramoni, and D. K. Panda,
_OC-DNN: Exploiting Advanced Unified Memory Capabilities in
CUDA 9 and Volta GPUs for Out-of-Core DNN Training_, 25th
IEEE International Conference on High-Performance Computing,
Data, Analytics, and Data Science (*HiPC '18*) '18, Dec 2018. 

. *A. A. Awan*, C-H Chu, X. Lu, H. Subramoni, and DK Panda,
_Can Unified-Memory support on Pascal and Volta GPUs enable
Out-of-Core DNN Training?_, ISC High-Performance (*ISC
'18*), June 2018. *Best Student Poster Award*.

. *A. A. Awan*, K. Hamidouche, J. Hashmi, and D. K. Panda,
_S-Caffe: Co-designing MPI Runtimes and Caffe for Scalable
Deep Learning on Modern GPU Clusters_, 22nd ACM SIGPLAN
Symposium on Principles and Practice of Parallel Programming
(*PPoPP '17*), Feb 2017.

. *A. A. Awan*, K. Hamidouche, A. Venkatesh, and D. K. Panda,
_Efficient Large Message Broadcast using NCCL and CUDA-Aware
MPI for Deep Learning_, 23rd European MPI Users' Group
Meeting (*EuroMPI '16*), Sep 2016. *Best Paper Runner-Up*.


=== All Publications

_Most updated list of publications is available from my https://scholar.google.com/citations?user=JM_IZzQAAAAJ&hl=en[Google Scholar] page._

====  Journal Articles
 
. *A. A. Awan*, A. Jain, C-H Chu, H. Subramoni, and DK Panda,
_Communication Profiling and Characterization of Deep
Learning Workloads on Clusters with High-Performance
Interconnects_, IEEE Micro (Early Access: doi:
10.1109/MM.2019.2949986).
 
. *A. A. Awan*, K. V. Manian, C-H Chu, H. Subramoni, and DK
Panda, _Optimized Large-Message Broadcast for Deep Learning
Workloads: MPI, MPI+NCCL, or NCCL2?_, Parallel Computing
(PARCO '19), Vol. 85, Pages 141-152, July 2019.
 
. C-H Chu, X. Lu, *A. A. Awan*, H. Subramoni, Bracy Elton, and
DK Panda, _Exploiting Hardware Multicast and GPUDirect RDMA
for Efficient Broadcast_, IEEE Transactions on Parallel and
Distributed Systems (TPDS '19), Vol. 30, No. 3, Pages
575-588, Mar 2019.
 
. K. Hamidouche, A. Venkatesh, *A. A. Awan*, H. Subramoni, and D. K. 
Panda, _CUDA-Aware OpenSHMEM: Extensions and Designs
for High Performance OpenSHMEM on GPU Clusters_, Parallel
Computing (PARCO '16), Vol. 58, Pages 27-36, Oct 2016.

. Z. Pervez, *A. A. Awan*, A. M. Khattak, S. Y. Lee, and
Eui-Nam Huh, _Privacy-aware searching with oblivious term
matching for cloud storage_, Journal of Supercomputing, Vol.
63, Issue 2, Pages 538–560, Feb 2013.
 
==== Refereed Conference/Workshop Papers
 
. A. Jain, *A. A. Awan*, H. Subramoni, and DK Panda, _Scaling
TensorFlow, PyTorch, and MXNet using MVAPICH2 for
High-Performance Deep Learning on Frontera_, 3rd Deep
Learning on Supercomputers Workshop, held in
conjunction with SC ‘19, Nov 2019.
 
. A. Jain, *A. A. Awan*, Q. Anthony, H. Subramoni, and DK
Panda, _Performance Characterization of DNN Training using
TensorFlow and PyTorch on Modern Clusters_, 21st IEEE
International Conference on Cluster Computing, (Cluster
'19), Sep 2019.

. *A. A. Awan*, A. Jain, C-H Chu, H. Subramoni, and D. K.
Panda, _Communication Profiling and Characterization of Deep
Learning Workloads on Clusters with High-Performance
Interconnects_, 26th Symposium on High-Performance
Interconnects (HotI ’19), Aug 2019.
 
. *A. A. Awan*, J. Bedorf, C-H Chu, H. Subramoni, and D. K. Panda, 
_Scalable Distributed DNN Training using TensorFlow and
CUDA-Aware MPI: Characterization, Designs, and Performance
Evaluation_, 19th IEEE/ACM International Symposium on
Cluster, Cloud and Grid Computing (CCGrid '19), May 2019.

 
. K. Vadambacheri Manian, *A. A. Awan*, A. Ruhela, C. Chu, 
and D. K. Panda, _Characterizing CUDA Unified Memory (UM)-Aware
MPI Designs on Modern GPU Architectures_, 12th Workshop on
General Purpose Processing Using GPU (GPGPU '19), held in
conjunction with
ASPLOS '19, Apr 2019.
 
. *A. A. Awan*, C-H Chu, X. Lu, H. Subramoni, and D. K. Panda,
_OC-DNN: Exploiting Advanced Unified Memory Capabilities in
CUDA 9 and Volta GPUs for Out-of-Core DNN Training_, IEEE
25th International Conference on High Performance Computing
(HiPC '18), Dec 2018.

. *A. A. Awan*, C-H Chu, H. Subramoni, D. K. Panda, _Optimized
Broadcast for Deep Learning Workloads on Dense-GPU
InfiniBand Clusters: MPI or NCCL?_, 25th European MPI Users'
Group Meeting (EuroMPI '18), Sep 2018.
 
. *A. A. Awan*, H. Subramoni, D. K. Panda, _An In-depth
Performance Characterization of CPU- and GPU-based DNN
Training on Modern Architectures_, 3rd Workshop on Machine
Learning in HPC Environments (MLHPC ‘17), held in
conjunction with SC ’17, Nov 2017.
 
. C-H Chu, X. Lu, *A. A. Awan*, H. Subramoni, J. Hashmi, Bracy
Elton, and DK Panda, _Efficient and Scalable Multi-Source
Streaming Broadcast on GPU Clusters for Deep Learning_,
46th International Conference on Parallel Processing (ICPP '17), Aug
2017.
 
. *A. A. Awan*, K. Hamidouche, J. Hashmi, and D. K. Panda,
_S-Caffe: Co-designing MPI Runtimes and Caffe for Scalable
Deep Learning on Modern GPU Clusters_, 22nd ACM SIGPLAN
Symposium on Principles and Practice of Parallel Programming
(PPoPP '17), Feb 2017.

. K. Hamidouche, *A. A. Awan*, A. Venkatesh, and D. K. Panda,
_CUDA M3: Designing Efficient CUDA Managed Memory-aware MPI
by Exploiting GDR and IPC_, 23rd IEEE International
Conference on High Performance Computing, Data, and
Analytics, Dec 2016.
 
. *A. A. Awan*, K. Hamidouche, A. Venkatesh, and D. K. Panda,
_Efficient Large Message Broadcast using NCCL and CUDA-Aware
MPI for Deep Learning_, 23rd European MPI Users' Group
Meeting (EuroMPI ‘16), Sep 2016. *Best Paper Runner-Up*.
 
. C. Chu, K. Hamidouche, A. Venkatesh, *A. A. Awan*, and D. K.
Panda, _CUDA Kernel based Collective Reduction Operations on
Large-scale GPU Clusters_, 16th IEEE/ACM International
Symposium on Cluster, Cloud and Grid Computing (CCGrid
‘16), May 2016.
 
. *A. A. Awan*, K. Hamidouche, A. Venkatesh, J. Perkins, H.
Subramoni, and D. K. Panda, _GPU-Aware Design,
Implementation, and Evaluation of Non-blocking Collective
Benchmark_, 22nd European MPI Users' Group
Meeting (EuroMPI ‘15), Sep 2015.
 
. K. Hamidouche, A. Venkatesh, *A. A. Awan*, H. Subramoni, 
and D. K. Panda, _Exploiting GPUDirect RDMA in Designing High
Performance OpenSHMEM for NVIDIA GPU Clusters_, IEEE
International Conference on Cluster Computing (Cluster '15),
Sep 2015.
 
. *A. A. Awan*, K. Hamidouche, C. Chu, and D. K. Panda, _A
Case for Non-Blocking Collectives in OpenSHMEM: Design,
Implementation, and Performance Evaluation using
MVAPICH2-X_, Workshop on OpenSHMEM and Related Technologies
(OpenSHMEM '15), Aug 2015.
 
. H. Subramoni, *A. A. Awan*, K. Hamidouche, D. Pekurovsky, A.
Venkatesh, S. Chakraborty, K. Tomko, and D. K. Panda,
_Designing Non-Blocking Personalized Collectives with Near
Perfect Overlap for RDMA-Enabled Clusters_, ISC High
Performance (ISC '15), Jul 2015.
 
. S. Chakraborty, H. Subramoni, J. Perkins, *A. A. Awan*, 
and D. K. Panda, _On-demand Connection Management for OpenSHMEM
and OpenSHMEM+MPI_ (HIPS '15), IPDPS Workshop, May 2015.
 
. *A. A. Awan*, M. S. Ayub, A. Shafi and S. Lee, _Towards
Efficient Support for Parallel I/O in Java HPC_, 13th
International Conference on Parallel and Distributed
Computing, Applications and Technologies (PDCAT '12), Dec
2012.
 
. M. B. Amin, W. A. Khan, *A. A. Awan*, and S. Y. Lee,
“Intercloud Message Exchange Middleware”, 6th International
Conference on Ubiquitous Information Management and
Communication (ICUIMC '12), Sep 2012. 

=== Posters

. *A. A. Awan* and DK Panda, _Co-designing Communication
Middleware and Deep Learning Frameworks for High-Performance
DNN Training on HPC Systems_, Doctoral Showcase at SC '19,
Nov 2019.


. *A. A. Awan*, H. Subramoni, and DK Panda, _Exploiting CUDA
Unified Memory for Efficient Out-of-Core DNN Training_,
Poster at NVIDIA GTC '19, April 2019.

. *A. A. Awan*, C-H Chu, X. Lu, H. Subramoni, and DK Panda,
_Can Unified-Memory support on Pascal and Volta GPUs enable
Out-of-Core DNN Training?_, ISC High-Performance (ISC '18), 
Jun 2018. *Best Student Poster Award*.

. *A. A. Awan* and DK Panda, _Co-designing MPI Runtimes and
Deep Learning Frameworks for Scalable Distributed Training
on GPU Clusters_, ACM Student Research Competition (SRC)
poster at SC '17, Nov 2017.

. *A. A. Awan*, M. B. Amin, S. Hussain, A. Shafi, S. Y. Lee,
_An MPI-IO Compliant Java based Parallel I/O Library_,
Poster at 13th IEEE/ACM International Symposium on Cluster,
Cloud and Grid Computing (CCGrid '13), May 2013.
